[package]
name = "chrome-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12.0"
actix-web = "4.0.0-beta.10"
actix-web-actors = "4.0.0-beta.7"
headless_chrome = {git="https://github.com/paulgb/rust-headless-chrome"}
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.1", features = ["env-filter"] }
actix-files = "0.6.0-beta.8"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.70"
